### ISSUE TITLE
Plugin prevents assignment displaying when it is disabled

### ISSUE THREAD

**Issue by mhughes2k** [jmcgettrick/MoodleDirectV2#108]
Whilst it is good that the Plagiarism plugin checks it is configured, the fact that the get_links() function doesn't appear to check if the whole module is turn on or off before it does something is annoying.

This really should be checked before anything else gets done....

~~There is an argument that the {{plagiarisum_load_available_plugins()}} code should only load enabled ones, but then they'd be active, rather than available, so on this basis the TII code should really double check...~~ it appears that it does... so why does the TII plugin think it still needs configured when it's disabled?!...

**Comment by jmcgettrick** [comment]
Hi @mhughes2k, apologies for the delay in getting this looked at. We've refactored the code to set and retrieve config data using Moodle functions and it's now in the develop branch. Thanks very much for the input!

We originally built the settings form as it is because we'd written a form output class for the mod/turnitintooltwo plugin and wanted to re-use that. We will look at refactoring this in the future if/when we add new configuration settings.
