### ISSUE TITLE
Instructors can see student names in anonymous assignments (PP)

### ISSUE THREAD

**Issue by micaherne** [jmcgettrick/MoodleDirectV2#160]
When using the plagiarism plugin, if an assignment is set up with blind marking enabled, instructors are able to see the full student name in the document viewer. 

As far as I can see, the "anonymous" setting on the Turnitin side is set correctly but the visibility of the full student name seems to be controlled by the post date, which in recent versions of the plugin is set to the same as the start date.

It seems to be possible to work around this by explicitly setting the post date via the "hidden until" setting in the grade column, but this isn't at all intuitive for lecturers, who expect to be able just to create an assignment with blind marking on and not see the student names until after it has been marked.

**Comment by jmcgettrick** [comment]
Hi Michael,
Yes, the two settings are confusing and ideally we would just use Moodle's blind marking setting. The problem we have in the plugin though is that anonymous marking is only available to UK Turnitin accounts. We will investigate to see if there are any reasons why we couldn't just use Moodle's blind marking setting but it will have to wait until anonymous marking is rolled out globally before we implement this in the plugin.
You are right with anonymous marking being post date dependent as well, names will always be shown once the post date has past. The idea with using the hidden until date was so that we didn't add another Turnitin setting but re-use Moodle settings to make the assignments as compatible as possible in both environments. We're always open to the idea of taking another look at an aspect though if it could be improved and made easier for the end user.
John

**Comment by hitteshahuja** [comment]
Hi John, 
We are currently investigating the same issue at our institution and we also strongly feel using the Hidden Until date adds an extra layer of complexity which might pose quite a challenge for tutors to get used to . You last line suggests that you are open to changing this to better suit end users needs and incidentally this does pose to us as a blocker to go ahead with Anonymous Marking at our institution, something we'd like to improve upon from a usability point of view .Hence I'd like to re-open this ticket  if possible or discuss this on a platform to get the conversation going. 
Your inputs in this matter ,as always ,are much valuable. 

Regards,
Hittesh
