### ISSUE TITLE
Incorrect calendar events

### ISSUE THREAD

**Issue by aruethe2** [jmcgettrick/MoodleDirectV2#183]
A faculty member created several Turnitin Assignment 2 activities, and then made several changes: adding and removing parts, renaming the assignments, and removing some of the assignments.  

Now the assignments are set up, but the Upcoming Events block does not reflect the correct assignment and part names.  

There are now 4 Turnitin Assignment 2 activities in the course:
![tii_activities](https://cloud.githubusercontent.com/assets/1678565/5859786/fc0bdaa6-a22a-11e4-832c-0dd1c0b85775.png)

Upcoming Events view:
![upcoming_events](https://cloud.githubusercontent.com/assets/1678565/5859788/009c33cc-a22b-11e4-90fd-728174c62d2a.png)

Note that the upcoming events shows several activities that don't exist (e.g. Sample case turn-it-in - Part 1) and shows duplicates in other places (e.g. Case 2 - Part 1).  The links from the Upcoming Events calendar seem almost random.  For example, Case 2 Part 1 in the events calendar actually links to the Case 4 activity.

Is this just a bug or is there some way to re-sync the calendar and activities?

**Comment by jmcgettrick** [comment]
Hi, we'll get this investigated.

**Comment by jmcgettrick** [comment]
Hi, we initially suspected this might be an issue with deleting individual parts but we can't replicate the error your having. Can you give me a bit more specifics as to how to replicate this?

**Comment by jmcgettrick** [comment]
Hi, we've managed to reproduce this and will get it fixed.

**Comment by jmcgettrick** [comment]
This has been fixed and released in 2015040101.

**Comment by Niki24** [comment]
Hi. We use Moodle as our primary LMS and utilize the Turnitin plugin. Since
upgrading to the latest version (2015040102), we have encountered an issue with
enrollment. When attempting to cross-list courses, and a course has
a Turnitin assignment, we receive the following error:

"moodle_database::update_record_raw()id field must be specified."
 
![capture](https://cloud.githubusercontent.com/assets/3390307/7441758/bd80a0b8-f0c3-11e4-98e8-624aa6aaf674.PNG)


On the backend this error is: 

"PHP Notice: Trying to get property of non-object in
/var/www/html/moodle/mod/turnitintooltwo/lib.php on line 168"

It appears that it's not passing the instance id to the parent course. 

We would appreciate your assistance in aiding this. Thank you for
your time. 

![capture1](https://cloud.githubusercontent.com/assets/3390307/7441773/36e87c14-f0c4-11e4-92dc-d1e6ac13a5dd.PNG)

**Comment by jmcgettrick** [comment]
Last comment is a different issue, I'm deleting it, see main issue here: https://github.com/jmcgettrick/MoodleDirectV2/issues/389#issue-72664590
