### ISSUE TITLE
PP does not update grades in Moodle if marked via Turnitin iPad app or if multiple submissions are marked without closing DV

### ISSUE THREAD

**Issue by tonyjbutler** [jmcgettrick/MoodleDirectV2#239]
Normally the updating of assignment grades in Moodle is triggered by an AJAX call when the DV window is closed. Obviously this doesn't happen if the teacher has accessed Grademark via a method other than clicking its icon in Moodle (e.g. if they are using the Turnitin iPad app instead) so the grade in Moodle only gets updated the next time the DV is opened and closed from Moodle.

A similar issue is experienced if the teacher launches the DV from Moodle and then grades multiple submissions for the same assignment by navigating between them using the navigation in the top right corner of the DV. In this case only the grade for the first submission graded (the one for which the DV was initially launched) is updated, and the rest of the grades remain in their previous state.

This patch adds a cron task to check for grades requiring an update from Grademark, and then triggers the update: https://github.com/lucisgit/MoodleDirectV2/commit/74b01e811d68a499304e9e6bc916b249d6b5e068

It also updates grades from Grademark which have been subsequently updated directly within the Moodle activity (see issue https://github.com/jmcgettrick/MoodleDirectV2/issues/240).

**Comment by jmcgettrick** [comment]
Closing as this has been followed up via email.

Thanks for the input again Tony.

**Comment by mhughes2k** [comment]
John can you say what is happening with this as we think we've seen this happening with staff who are using the iPad app (we don't officially support their use ;-) )

Is it fixed, to be fixed or something else ?

**Comment by tonyjbutler** [comment]
John, this issue has not been resolved and a resolution is very much needed. I have merely been informed that my patch results in too much additional load on the Turnitin servers. I will continue to work on it.

Please re-open. Thanks.

**Comment by jmcgettrick** [comment]
Hi, 

I closed this issue initially as my colleague had contacted you via email. The issue we have is that if a grade is updated outwith the plugin we have no way from within the plugin of identifying the specific submission(s) that has/have been graded elsewhere. Because of this, we would therefore have to check every submission in every assignment to be sure that grades were correctly in sync.

With even small institutions this could easily run into thousands of requests, which when run in a live environment by numerous institutions could be detrimental to the stability of our service, and is therefore not feasible for us include in the supported versions of the plugin at this stage.

An idea that has came out of an initial discussion looking for an alternative is to replicate the "refresh submissions" button, similar to what we have in the Turnitin Assignment module. This would update all the grades and similarity scores for an assignment, we'll investigate this further and get back to you with a solution.

**Comment by tonyjbutler** [comment]
We've discussed that option too, and concluded that it would not be an adequate solution. I don't think it is realistic to provide a mobile app for marking and then expect users to log into Moodle to manually upda

**Comment by alexumn** [comment]
Grading multiple items in the Turnitin DV and not having all grades come back to the Moodle Assignment is becoming a major problem at our institution as well.

From a user perspective, the best solution would involve pulling all submission grades for the assignment from Turnitin into the Moodle Assignment, upon DV close, and not involve cron. If that is technically feasible, that step would need to be in 500 object batches to not run into the Turnitin API's 500 object limit.

**Comment by jmcgettrick** [comment]
Hi Tony, my colleague has emailed you but for the benefit of everyone else, we're going to refresh results for the assignment when closing the Document Viewer similar to what @alexumn suggested. We'll store a timestamp for the relevant assignment in the plagiarism_turnitin_config database so that we are only synching results from a set point and not updating all submissions in the assignment. We hope to get this out as part of 2014012414 which will tentatively be towards the end of March.

**Comment by tonyjbutler** [comment]
Thanks John. This seems like a sensible solution for teachers updating multiple submissions via the DV, but how does it deal with submissions graded outside of the Moodle integration entirely (e.g. via your iPad app)?

**Comment by jmcgettrick** [comment]
Hi Tony, it will get the grades from Turnitin so it will update any submission that was graded via the iPad as long as they have been synced to Turnitin

**Comment by tonyjbutler** [comment]
But how is the update triggered if not by either a cron task or a DV open/close?

**Comment by jmcgettrick** [comment]
It'll refresh the grades when opening/closing the DV, we'll also put a refresh button in the module settings which will refresh the grades as well. It's not an ideal place to have it but we don't have control of much of the screen in the inbox view.

**Comment by jmcgettrick** [comment]
This was released in 2015040101.

**Comment by ianmcn** [comment]
I've just installed 2015040102 in order to fix this issue, but I can't see
how to synchronise the grades. I've opened and closed the DV, but it's not
updated the grades in Moodle. Should it happen instantly? I've looked for
the Refresh button in the module settings, but can't find it. What page are
you referring to?

**Comment by jmcgettrick** [comment]
In the assignment module settings under the Turnitin plagiarism plugin settings, there is a link on the right hand side to refresh submissions.
![moodle-assign-settings-pp](https://cloud.githubusercontent.com/assets/5583704/7563443/28a96b1e-f7d5-11e4-9f8c-99db79f7b586.png)
.

**Comment by ianmcn** [comment]
OK, that's for the Assignment activity but what about the "Turnitin
Assignment 2" activity type? The "Refresh Submissions" link on the inbox
doesn't sync the grades back to the Moodle Gradebook. I managed to solve it
in the end by changing the needs_updating field in mdl_turnitintooltwo
table to "1", then running the cron. Not sure if this was the best way to
do it, but it seemed to get the job done. Does this fix only apply to the
Moodle Assignment type or to the Turnitin Assignment 2 type as well?

**Comment by jmcgettrick** [comment]
The Refresh Submissions links both work based on a timestamp and only refresh submissions modified since <TIMESTAMP>. The plagiarism plugin stores this in the database but the Turnitin Assignment only stores it in the session. The first time you login it should refresh everything then it will set a timestamp that is used throughout the session.

**Comment by ianmcn** [comment]
OK, so how does it catch submissions graded on the iPad app? They could
have been graded before the timestamp is set.

**Comment by jmcgettrick** [comment]
The Turnitin Assignment won't have a session timestamp set the first time you visit it, so it will update everything. The time that the submissions are synced back to Turnitin date will be the time that the submission was last modified.
