### ISSUE TITLE
moodledata/temp/turnitintooltwo storing files and not clearing out

### ISSUE THREAD

**Issue by Syxton** [jmcgettrick/MoodleDirectV2#402]
We have found 1200+ files in this folder on moodledata.  Are these files supposed to be cleared out eventually?

**Comment by jmcgettrick** [comment]
We don't have a process that clears them out as we leave file upload entirely to Moodle to deal with. You can remove them manually through the files tab in the settings area though.

We don't actually use the original file in moodledata once it has gone to Turnitin, all our access goes through Turnitin so they could probably be removed.

**Comment by danmarsden** [comment]
Hi John - I'm not sure that is correct behaviour. Typically Moodle processes that use the temp folder will clean up after themselves - I suspect you may need to re-open this.

**Comment by danmarsden** [comment]
it looks like you are creating your own root "temp" dir:
https://github.com/jmcgettrick/MoodleDirectV2/blob/master/mod/turnitintooltwo/lib.php#L612

you should be using $CFG->tempdir there instead of suffixing dirroot with "temp"

that means if anyone defines a different location for their tempdir any internal processes that clean up the moodle tempdir automatically won't work within your own created directory.

There is a central process that is supposed to clean up files older than 1 week in the tempdir location but this is supposed to be a catch-all rather than the behaviour to rely on. Typically processes that create temp files will delete them after they have been used. For example the normal backup/restore process will create files in the tempdir location while running but will delete the data after the task has completed. The only time it leaves data there is in the case of a backup/restore failure so the code progression doesn't complete. There are also other methods like send_temp_file which delete the file after sending to the browser.

FYI - Moodle 2.9 adds a new option that allows the admin to control how often the files in the CFG->tempdir are removed (https://tracker.moodle.org/browse/MDL-32547)

**Comment by jmcgettrick** [comment]
Thanks @danmarsden we'll get this looked at.

**Comment by jmcgettrick** [comment]
This has been fixed and released in 2015040106. The Turnitin Assignment was deleting temp files, but the plagiarism plugin wasn't. That's now been rectified.
