### ISSUE TITLE
Post date is the same as Start Date

### ISSUE THREAD

**Issue by barrysspace** [jmcgettrick/MoodleDirectV2#486]
When setting up a Moodle assignment with the Tii plagiarism plugin enabled, the 'Post date' in www.turnitinuk.com matches the start date. There is no option within the plagiarism plugin on Moodle to amend 'Post date'. As a result anything done by the convenor on GradeMark is immediately made available to the student regardless of what Moodle restrictions are put on such as Workflow (except hiding the assignment). This includes the mark given on GradeMark and any comments added on GradeMark.

![post date same as start date](https://cloud.githubusercontent.com/assets/7804636/9628248/7e36c154-5161-11e5-87f0-d92d9dcc7127.jpg)

**Comment by jmcgettrick** [comment]
Hi @barrysspace, initially when the plugin was first released we used the Moodle assignment due date to double as the post date in Turnitin but this was causing issues with students not able to see grades because the due date is pushed out to account for late submissions. 

The current workflow we now use to resolve this was that if a post date was desired for an assignment, the institution could achieve this by setting a hidden until date for the relevant module in the Moodle Gradebook. The reasoning behind this was to attempt to fit in with Moodle's grading workflow as best as we could.

We are looking into how we can improve this though and welcome any suggestions.
